name: Load Tests

on:
  workflow_dispatch:
    inputs:
      SCENARIO:
        type: 'choice'
        default: './scenarios/get_operation_with_seeds/v1.0.conf'
        options:
          - ./scenarios/get_operation_with_seeds/v1.0.conf
          - ./scenarios/get_operation_without_seeds/v1.0.conf
        required: true
        description: 'Locust config file'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create report directory
        run: mkdir -p ./reports/${{ github.run_id }}

      - name: Run load tests and generate HTML report
        run: locust --config=${{ github.event.inputs.SCENARIO }} --html=./reports/${{ github.run_id }}/index.html

      - name: Upload Locust reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports

  publish-report:
    if: always()
    needs: [ run-tests ]
    runs-on: ubuntu-latest

    steps:
      - name: Download Locust reports
        uses: actions/download-artifact@v4
        with:
          name: reports
          path: reports

      - name: Deploy HTML report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          keep_files: true
          publish_dir: reports
          publish_branch: gh-pages